<?php

return array (
  'C2' => '<p>Speech characterised by <b>precision, appropriateness and ease with the language.</b></p><p>Can convey finer shades of meaning precisely, by using, with reasonable accuracy, a wide range of modification devices.</p><p>Can backtrack and restructure around a difficulty so smoothly the interlocutor is hardly aware of it.</p><p>Can produce clear, smoothly flowing well-structured speech with an effective logical structure.</p>',
  'C1' => '<p>Has good access to a broad range of language, which allows <b>fluent, spontaneous communication.</b></p><p>There is little obvious searching for expressions or avoidance strategies.</p><p>Can give clear, detailed descriptions and presentations on complex subjects, developing particular points and rounding off with an appropriate conclusion.</p>',
  'B2+' => '<p><b>Focus on argument, effective social discourse and language awareness.</b></p><p>Can use the language fluently, accurately and effectively on a wide range of general, academic, vocational or leisure topics, marking clearly the relationships between ideas.</p><p>Can communicate spontaneously without much sign of having to restrict what he/she wants to say.</p><p>Can give clear, systematically developed descriptions and presentations, with appropriate highlighting of significant points, and relevant supporting detail.</p>',
  'B2' => '<p>Can interact with a degree of fluency and spontaneity that makes regular interaction, and sustained relationships with speakers of the target language quite possible <b>without imposing strain on either party.</b></p><p>Can highlight the personal significance of events and experiences and sustain views clearly by providing <b>relevant explanations and arguments.</b></p><p>Can give clear, detailed descriptions and presentations on a wide range of subjects related to his/her field of interest, expanding and supporting ideas with subsidiary points and relevant examples. Can construct a chain of reasoned argument.</p>',
  'B1+' => '<p>Can communicate with <b>some confidence</b> on familiar routine and non-routine matters related to his/her interests and professional field.</p><p>Can deal with less routine situations and explain why something is a problem.</p><p>Can express thoughts on more abstract, cultural topics such as films, books, music etc.</p>',
  'B1' => '<p>Has the ability to <b>get across what he wants to say</b> and can maintain a conversation, but may sometimes be difficult to follow when trying to say exactly what he/she would like to.</p><p>Can reasonably fluently sustain a straightforward description of one of a variety of subjects within his/her field of interest, presenting it as a <b>linear sequence of points.</b></p>',
  'A2+' => '<p><b></b>Can interact with reasonable ease in structured situations and short conversations, <b>provided the other person helps if necessary.</b></p><p><b></b>Can have a conversation about familiar topics in predictable everyday situations, though he/she<b> will generally have to compromise the message and search for words.</b></p>',
  'A2' => '<p>Can communicate in simple and routine tasks requiring a simple and direct exchange of information on familiar matters, but <b>is rarely able to understand enough to keep conversation going of his/her own accord.</b></p><p>Can give a <b>simple description</b> of people, living or working conditions, daily routines, likes/dislikes etc. <b>as a short series of simple phrases and sentences linked into a list.</b></p>',
  'A1' => '<p>Can interact in a simple way but communication is <b>totally dependent on repetition at a slower rate of speech</b>, rephrasing and repair.</p><p>Can answer and ask simple questions, initiate and respond to simple statements in areas of immediate need or on very familiar topics.</p><p>Can produce <b>simple mainly isolated phrases</b> about people and places.</p>',
  'Pre-A1' => '<p>Can answer questions about him/herself and daily routines, using <b>short, formulaic expressions.</b></p><p>Can give basic personal information (e.g. name, address, family, nationality).</p>',
);
